development:
  adapter: mysql
  encoding: utf8
  database: wufoo_development
  username: root
  password: root

test:
  adapter: mysql
  encoding: utf8
  database: wufoo_test
  username: root
  password: root
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: wufoo_production
  username: root
  password: root